// Runtime mirror of docs/design/01_核心机制与数值.md. Scenario prices live with their scenario.
export const RULES = {
  days: 14,
  ap: 10,
  borrowMax: 4,
  borrowCapLoss: 1,
  overtimeCapLoss: 2,
  overtimeStamina: 5,
  cash: 3000,
  rent: 1200,
  living: 40,
  wages: 2100,
  wageDays: [7, 14],
  nightPay: 100,
  debtRate: 0.03,
  debtMax: 50000,
  debtGrace: 2,
  familyFunding: 5000,
  assetSale: 3500,
  consultationPay: 140,
  goodCasePay: 200,
  budgetShare: 1,
  coffeeCost: 15,
  dc: [9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
  pressure: [0, 0, 1, 2, 3, 4, 5, 6, 8, 10, 12, 14, 16, 18],
  patientCount: [1, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5],
  nightDays: [3, 6, 9, 12, 14],
  nightBudget: [240, 220, 200, 180, 180],
  nightCases: [2, 2, 3, 3, 3],
  ward: {
    expectedMin: 2,
    expectedMax: 4,
    dailyCost: 180,
    overdueMultiplier: 1.5,
    stabilityNeed: 2,
    reviewStability: 1,
    neglectStability: -1,
    capacity: 12,
    firstBed: 5,
    initialCensus: 3,
    initialStay: 2,
    initialStableCount: 1,
    arrivals: [0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2],
    handoverStability: 1,
    initialPatience: 80,
    observationDailyCost: 90,
    transferAp: 1,
    transferMinutes: 20,
    transferCost: 0,
    patienceDaily: 4,
    patienceOverdue: 12,
    explanationGain: 18,
    lowPatience: 25,
    reviewCost: 100,
    appealAp: 2,
    extensionRate: 0.15,
    appealGrantRate: 0.2,
    earlyReturnChance: 0.8,
    earlyDischargeRisk: 55,
    maxCards: 12,
  },
  meta: {
    skillCost: 3,
    skillMax: 3,
    capCost: 4,
    capRank: 5,
    capMax: 3,
    cashCost: 2,
    cashMax: 3,
    cashStep: 1000,
  },
} as const;
export const VITAL_LABELS = {
  stamina: "体力",
  san: "精神",
  emotion: "情绪",
} as const;
export const RELATION_LABELS = {
  chief: "主任",
  nurse: "护士长",
  peer: "同事",
  family: "家人",
} as const;
export const SKILL_LABELS = {
  observe: "观察力",
  clinical: "临床",
  record: "文书",
  persuade: "说服",
  comfort: "安抚",
  endure: "耐受",
} as const;
export const ACTORS: Record<
  string,
  { name: string; role: string; portrait: string }
> = {
  chief: { name: "唐济", role: "科主任", portrait: "tang" },
  nurse: { name: "姜蓉", role: "护士长", portrait: "jiang" },
  peer: { name: "李恂", role: "住院医师", portrait: "li" },
  research: { name: "周乔", role: "科研同事", portrait: "zhou" },
  rep: { name: "叶茗", role: "医药代表", portrait: "ye" },
  father: { name: "父亲", role: "来电", portrait: "father" },
};
