// Runtime mirror of docs/design/01_核心机制与数值.md. Scenario prices live with their scenario.
export const RULES = {
  days: 14,
  sanRescueChances: 1,
  critical: {R:5,C:10,D:10,sanLoss:5},
  ap: 10,
  borrowMax: 4,
  borrowCapLoss: 1,
  overtimeCapLoss: 2,
  overtimeStamina: 5,
  cash: 3000,
  rent: 1200,
  living: 40,
  wages: 2100,
  wageDays: [7, 14],
  nightPay: 100,
  extraShift:{fullMinutes:200,partialMinutes:100,fullCases:2,partialCases:1,completionSan:5,peerFavor:1},
  peerReferrals:{patients:3,fullAp:3,briefMinutes:2,briefDocumentationRisk:5},
  debtRate: 0.03,
  debtMax: 50000,
  debtGrace: 2,
  incomeWindow:7,
  familyFunding: 5000,
  creditPressure: 20,
  halfDayAp: 4,
  assetSale: 3500,
  consultationPay: 140,
  performance: { goodMin: 80, goodMax: 300, budgetRate: .05, roundTo: 10, ordinary: 40 },
  budgetShare: 1,
  billing:{inpatientBaseRate:.6,outpatientBaseRate:.08},
  coffeeCost: 15,
  dc: [9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
  pressure: [0, 0, 1, 2, 3, 4, 5, 6, 8, 10, 12, 14, 16, 18],
  patientCount: [1, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5],
  nightDays: [3, 6, 9, 12, 14],
  nightBudget: [240, 220, 200, 180, 180],
  nightCases: [2, 2, 3, 3, 3],
  nightIncident:{stamina:8,san:5,hallucinationSan:3},
  nightOverrun:{stamina:5,san:3},
  deferredPatient:{R:10,D:10,hiddenSeedChance:.3},
  weeklyOverspend:{notice:3000,interview:8000,emotion:10,reputation:5},
  audit:{weightMax:2,weightPerPoint:.08,echoThresholds:[3,6,9],echoAp:[1,2,3],echoDelayMin:1,echoDelayMax:3},
  events:{echoDailyCaps:[0,0,0,1,1,1,1,2,2,2,2,3,3,3]},
  family:{deathChance:.3,bereavementSan:20,bereavementDepression:15},
  butterfly:{handoffAp:1,bridgeLoan:10000,loanDays:7,nonpaymentRoll:8,cooperationExitEmotion:5,deadlineExtensionDays:1,paperDeadline:11,permissionDc:12,unconditionalOfferChance:.4,liaisonOfferDay:9,liaisonDailyAp:1,liaisonDailyMinutes:10,liaisonMissEmotion:2,peerExamPreludeStart:3,peerExamPreludeEnd:12,peerExamPreludeChance:.25},
  handoverTranscription:{start:2,end:13,chance:.35,carefulAp:1,carefulMinutes:8,memoryMinutes:2,memoryEmotion:2,dc:12},
  nightTelephone: {risk:25,seedChance:.7,minutes:5},
  perception: {
    tense: 70, distorted: 50, fractured: 30,
    tired: 50, exhausted: 30, socialPenalty: 2,
    hallucinationAp: 1, hallucinationMinutes: 5,
    nightExtraSan: 3,
  },
  ward: {
    expectedMin: 2,
    expectedMax: 4,
    dailyCost: 180,
    overdueMultiplier: 1.5,
    stabilityNeed: 2,
    reviewStability: 1,
    neglectStability: -1,
    capacity: 12,
    firstBed: 5,
    initialCensus: 5,
    initialStay: 2,
    initialStableCount: 2,
    arrivals: [0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2],
    handoverStability: 1,
    initialPatience: 80,
    observationDailyCost: 90,
    transferAp: 1,
    transferMinutes: 20,
    transferCost: 0,
    patienceDaily: 4,
    patienceOverdue: 12,
    explanationGain: 18,
    lowPatience: 25,
    reviewCost: 100,
    appealAp: 2,
    extensionRate: 0.15,
    appealGrantRate: 0.2,
    earlyReturnChance: 0.8,
    earlyDischargeRisk: 55,
    maxCards: 12,
  },
  meta: {
    skillCost: 3,
    skillMax: 3,
    capCost: 4,
    capRank: 5,
    capMax: 3,
    cashCost: 2,
    cashMax: 3,
    cashStep: 1000,
    fourthSlotCost:40,
    redrawCost:3,
    redrawMax:5,
    rerollCost:10,
    attendingCost:20,
    depressionCost:3,
    depressionMax:2,
  },
  abilities:{transferDc:12},
} as const;
export const VITAL_LABELS = {
  stamina: "体力",
  san: "精神",
  emotion: "情绪",
} as const;
export const RELATION_LABELS = {
  chief: "主任",
  nurse: "护士长",
  peer: "同事",
  family: "家人",
} as const;
export const SKILL_LABELS = {
  observe: "观察力",
  clinical: "临床",
  record: "文书",
  persuade: "说服",
  comfort: "安抚",
  endure: "耐受",
} as const;
export const ACTORS: Record<
  string,
  { name: string; role: string; portrait: string }
> = {
  chief: { name: "唐济", role: "科主任", portrait: "tang" },
  nurse: { name: "姜蓉", role: "护士长", portrait: "jiang" },
  peer: { name: "李恂", role: "住院医师", portrait: "li" },
  research: { name: "周乔", role: "科研同事", portrait: "zhou" },
  rep: { name: "叶茗", role: "医药代表", portrait: "ye" },
  father: { name: "父亲", role: "来电", portrait: "father" },
  mother: { name: "母亲", role: "来电", portrait: "mother" },
  auditor: { name: "医保稽核员", role: "医保与费用核查", portrait: "tang" },
};
