import type { Effects, Option, Story, Condition } from "./types";

const o = (
  id: string,
  label: string,
  ap: number,
  cash: number,
  result: string,
  effects: Effects = {},
  when?: Condition,
): Option => ({
  id,
  label,
  ap,
  minutes: ap * 15,
  cost: 0,
  result,
  effects: { ...effects, cash: (effects.cash ?? 0) + cash },
  when,
});
const risk = (
  type: "R" | "C" | "D" | "F",
  weight: number,
  reason: string,
  norm: string,
  causal = false,
) => ({ type, weight, reason, norm, causal });
const s = (
  id: string,
  day: number,
  actor: string,
  chain: string,
  title: string,
  text: string,
  options: Option[],
  after?: string,
  when?: Condition,
): Story => ({
  id,
  day,
  actor,
  chain,
  title,
  text,
  options,
  after,
  when,
  scope: {
    kind: chain === "research" ? "project" : "personal",
    id: chain === "research" ? "lung-registry" : chain,
  },
});

export const STORIES: Story[] = [
  s(
    "shift-1",
    1,
    "peer",
    "shift",
    "空着的那一格",
    "李恂把排班表推过来。「今晚能替我值两个小时班吗？我爸要去做检查，没人陪他。」你看见他的名字下面还有橡皮擦过的灰。",
    [
      o(
        "shift-1-a",
        "接下这两个小时",
        2,
        0,
        "李恂把钥匙交给你。你坐到了他的电脑前，直到他回来。",
        {
          stamina: -8,
          relations: { peer: 1 },
          flags: ["shift-covered", "li-owes-time"],
        },
      ),
      o(
        "shift-1-b",
        "把调班申请递给护士长",
        1,
        0,
        "姜蓉重新安排了人手。李恂把申请单收进包里。",
        {
          relations: { nurse: 1, peer: -1 },
          emotion: -3,
          flags: ["shift-formal"],
        },
      ),
      o(
        "shift-1-c",
        "拒绝，留时间查房",
        0,
        0,
        "李恂删掉了没发出的消息，打电话给家里。",
        { relations: { peer: -1 }, emotion: -5, flags: ["shift-refused"] },
      ),
    ],
  ),
  s(
    "cash-1",
    1,
    "peer",
    "cash",
    "借出去的现金",
    "李恂发来一张缴费单。「能借我三千元吗？等我发了工资就还你。」你刚付过房租，打开手机银行看了看余额。",
    [
      o(
        "cash-1-a",
        "借他 ¥3,000",
        0,
        -3000,
    "你把钱转给李恂，在聊天里保留了借款金额和还款日期。",
        {
          receivable: 3000,
          emotion: -3,
          relations: { peer: 1 },
          flags: ["lent-li"],
        },
      ),
      o("cash-1-b", "借他 ¥1,500", 0, -1500, "李恂收款后，又拨了一个电话。", {
        receivable: 1500,
        relations: { peer: 1 },
        flags: ["lent-li"],
      }),
      o(
        "cash-1-c",
        "不借钱，陪他办缓缴",
        1,
        0,
    "你陪李恂办好了缓缴，领到延期单时，已经错过午饭了。",
        { stamina: -4, flags: ["helped-deferral"] },
      ),
    ],
  ),
  s(
    "research-1",
    2,
    "research",
    "research",
    "课件中的三页",
    "周乔翻到课件末尾。「你先存好这三页吧，下周汇报要用。我再去找它们的出处。」你看了看图，上面没有原始数据链接。",
    [
      o(
        "research-1-a",
        "只存作待核资料",
        0,
        0,
        "你给文件加了待核标记。它没有进入汇报稿。",
        { emotion: -2, flags: ["slides-held"] },
      ),
      o(
        "research-1-b",
        "核对来源再整理",
        2,
        0,
        "你找到其中两页的原始材料，第三页的样本数对不上。",
        {
          stamina: -4,
          flags: [
            "slides-held",
            "research-known-problem",
            "research-originals",
          ],
        },
      ),
      o(
        "research-1-c",
        "退回，要求原始数据",
        0,
        0,
        "周乔合上电脑。「那就先空着。」",
        { relations: { peer: -1 }, flags: ["slides-refused"] },
      ),
    ],
  ),
  s(
    "record-1",
    2,
    "nurse",
    "record",
    "屏幕朝下的手机",
    "姜蓉叫你去谈话室。患者女儿把正在录音的手机放在桌上。「医生，你先跟我说清楚，我爸得住几天院，要花多少钱？」",
    [
      o(
        "record-1-a",
        "说明估计与尚未排除的风险",
        1,
        0,
        "你说明病情、费用和出院条件，没有保证日期。她把录音留在自己的手机里。",
        {
          stamina: -2,
          flags: ["recording-exists", "recording-honest"],
          relations: { nurse: 1 },
        },
      ),
      o(
        "record-1-b",
        "保证三天内出院",
        0,
        0,
    "你说：“他三天内就能出院。”她的手机完整录下了这句话。",
        {
          emotion: 2,
          flags: ["recording-exists", "discharge-promise"],
          hazards: [
            risk(
              "C",
              20,
              "在风险未明时承诺固定出院日期",
              "沟通不得替代临床出院评估",
            ),
          ],
        },
      ),
      o(
        "record-1-c",
        "请她停录后再谈",
        0,
        0,
        "她没有停录。你结束了这次谈话，姜蓉留下继续解释。",
        {
          relations: { nurse: -1 },
          emotion: -6,
          flags: ["recording-exists", "recording-refused"],
        },
      ),
    ],
  ),
  s(
    "shift-2",
    3,
    "father",
    "shift",
    "急诊缴费窗口",
    "母亲来电，父亲被车碰倒，刚送进另一家医院。她报了两次楼层，最后问：「你现在能过来吗？」",
    [
      o(
        "shift-2-a",
        "请李恂兑现顶班，赶去医院",
        1,
        -800,
    "你把交班事项逐条告诉李恂，他接手了病区的工作。你赶到医院时，母亲正在电梯口等你。",
        {
          flags: ["father-accident", "father-seen", "li-favor-used"],
          relations: { family: 1 },
          emotion: -8,
          depression: 5,
        },
        { all: ["li-owes-time"] },
      ),
      o(
        "shift-2-b",
        "办正式交班，请假过去",
        2,
        -800,
        "二线接管病区。你赶到时，父亲的衣服装在一个塑料袋里。",
        {
          flags: ["father-accident", "father-seen"],
          relations: { chief: -1, family: 1 },
          emotion: -8,
          depression: 5,
        },
      ),
      o(
        "shift-2-c",
        "留在病区，只转钱",
        0,
        -1200,
        "你发了转账。下一通电话响起时，你正在核对医嘱。",
        {
          flags: ["father-accident", "father-missed"],
          relations: { family: -1 },
          emotion: -12,
          san: -5,
          depression: 5,
        },
      ),
    ],
    "shift-1",
  ),
  s(
    "cash-2",
    3,
    "father",
    "cash",
    "押金",
    "母亲拍下缴费单发给你，上面列着护理和检查费用，旁边还记了交通费。「得先补五千元，你那边的钱够不够啊？」",
    [
      o(
        "cash-2-a",
        "付 ¥5,000",
        0,
        -5000,
    "母亲收到了你转过去的钱，说会把每张单据留好。",
        { emotion: -6, flags: ["family-deposit-paid"] },
      ),
      o(
        "cash-2-b",
        "申请救助和分期缴费",
        2,
        -1200,
    "窗口工作人员收下你的申请，母亲陪你复印了申请材料。",
        { stamina: -5, emotion: -5, flags: ["family-aid"] },
      ),
      o(
        "cash-2-c",
        "让家里先动用存款",
        0,
        0,
        "母亲说：“知道了，你先忙。”当天晚上，她没再打电话。",
        { relations: { family: -1 }, san: -6, flags: ["family-savings-used"] },
      ),
    ],
    "cash-1",
  ),
  s(
    "research-2",
    4,
    "research",
    "research",
    "共用的署名栏",
    "周乔要你接管登记项目的表格。「你每天抽一个小时来整理，我给你署共同第一作者。先把格式补齐就行，缺的数据可别编啊。」",
    [
      o(
        "research-2-a",
        "接下核查工作",
        2,
        0,
        "你核完当天能找到的原件，写下仍缺的记录。",
        { stamina: -6, flags: ["research-worked", "research-originals"] },
      ),
      o(
        "research-2-b",
        "只接受挂名",
        0,
        0,
        "你的名字进了内部草稿，原件没有经过你的手。",
        { relations: { chief: 1 }, emotion: -3, flags: ["research-name-only"] },
      ),
      o(
        "research-2-c",
        "退出署名，留在病区",
        0,
        0,
        "周乔删掉了你的名字。汇报群里少了一次提醒。",
        { relations: { chief: -1 }, flags: ["research-withdrawn"] },
      ),
    ],
    "research-1",
  ),
  s(
    "record-2",
    4,
    "nurse",
    "record",
    "她只告诉了你",
    "患者女儿在走廊拦住你。「保险的事，我爸还不知道。录音别发到家族群里。他一听钱就要回家。」",
    [
      o(
        "record-2-a",
        "记录授权范围，另谈费用",
        1,
        0,
        "她确认只向医务科提供必要片段。你留了完整原件的保管记录。",
        { flags: ["record-scope-known", "record-original-held"], emotion: -2 },
      ),
      o(
        "record-2-b",
        "让她去找医保窗口",
        0,
        0,
        "她拿着单子去了楼下，没再谈录音。",
        { emotion: -3, flags: ["record-scope-unknown"] },
      ),
      o(
        "record-2-c",
        "把她的话转给其他家属",
        0,
        0,
        "家族群里出现了那段话。她回来问是谁发的。",
        {
          flags: ["privacy-shared"],
          emotion: -8,
          hazards: [
            risk(
              "C",
              25,
              "未经授权转发家庭私密信息",
              "隐私披露须有必要性和授权范围",
            ),
          ],
        },
      ),
    ],
    "record-1",
  ),
  s(
    "shift-3",
    5,
    "peer",
    "shift",
    "没做的查体",
    "李恂指着自己的病程记录。「我昨晚没来得及给患者查体，你能不能帮我证明我查过了？主任就问了这一项。」",
    [
      o(
        "shift-3-a",
        "只确认自己在场的时段",
        1,
        0,
        "你写下亲历的时间，没有替他补出一次查体。",
        { relations: { peer: -1 }, flags: ["li-truthful-witness"] },
      ),
      o(
        "shift-3-b",
        "替他签下“已查体”",
        0,
        0,
        "你签了。电子记录保存了签名和提交时间。",
        {
          relations: { peer: 1 },
          flags: ["li-false-witness"],
          hazards: [
            risk(
              "D",
              35,
              "为他人的未实施查体出具虚假证明",
              "证言只证明亲历事实",
            ),
          ],
        },
      ),
      o(
        "shift-3-c",
        "拒绝签字，也不作证明",
        0,
        0,
        "李恂把页面关掉。「行，知道了。」",
        { relations: { peer: -2 }, emotion: -4, flags: ["li-witness-refused"] },
      ),
    ],
    "shift-2",
  ),
  s(
    "cash-3",
    5,
    "peer",
    "cash",
    "还款日",
    "李恂说今天只能拿出一半。他把转账页面打开，让你看了一眼余额。",
    [
      o(
        "cash-3-a",
        "收回一半，余款延期",
        0,
        0,
        "李恂转来欠款的一半，余款写进聊天记录。",
        { flags: ["li-half-repaid"], emotion: -2 },
        { all: ["lent-li"] },
      ),
      o(
        "cash-3-b",
        "不催，帮他再跑一趟窗口",
        1,
        0,
        "你们在窗口前排到下班。他没有拿出更多钱。",
        { stamina: -4, relations: { peer: 1 }, flags: ["li-deferred-again"] },
      ),
      o(
        "cash-3-c",
        "把借款与工作分开",
        0,
        0,
        "你说清还款日期，不接受用签字或顶班抵钱。",
        { relations: { peer: -1 }, flags: ["li-debt-boundary"] },
      ),
    ],
    "cash-2",
    { all: ["lent-li"] },
  ),
  s(
    "research-3",
    6,
    "chief",
    "research",
    "主任的笔",
    "唐济把汇报首页放到你面前。「项目得做，病区也得有人管，你两边都要交代清楚。今天下班前，把整理好的汇报交给我。」",
    [
      o(
        "research-3-a",
        "只交已核对部分",
        2,
        0,
    "你把没核实的部分留空，在页脚列出未解决的问题。唐济看完汇报，没有签字。",
        { emotion: -5, flags: ["research-partial-shown"] },
      ),
      o(
        "research-3-b",
        "拿待核三页凑成完整汇报",
        0,
        0,
    "你把来源还没核实的三页材料放进内部汇报稿。唐济在封面上签了字。",
        {
          relations: { chief: 1 },
          flags: ["slides-used-internal"],
          hazards: [
            risk(
              "D",
              15,
              "未经核查的材料作为项目汇报结果",
              "项目资料须区分原始证据与待核材料",
            ),
          ],
        },
        { all: ["slides-held"] },
      ),
      o(
        "research-3-c",
        "放弃这次考核名额",
        0,
        0,
    "你放弃了考核名额，封面上也划掉了你的名字。随后，你回到护士站。",
        {
          relations: { chief: -1 },
          emotion: -8,
          flags: ["promotion-abandoned"],
        },
      ),
    ],
    "research-2",
  ),
  s(
    "record-3",
    6,
    "nurse",
    "record",
    "第四天的录音",
    "谈话室的门开着。女儿拿出第一天的录音，问当初那句话还算不算数。她的律师正在电话另一头听。",
    [
      o(
        "record-3-a",
        "逐句核对，再谈当前病情",
        2,
        0,
    "你核对了当时说过的话，再记下患者目前的病情和出院条件。她要求拿走记录的副本。",
        { flags: ["record-reviewed"], emotion: -5, relations: { nurse: 1 } },
      ),
      o(
        "record-3-b",
        "说自己没有作过保证",
        0,
        0,
        "她把手机放到桌上，按下播放键。你这次的回答也被录了下来。",
        {
          flags: ["denied-recording"],
          emotion: -6,
          hazards: [
            risk("C", 15, "未核对原始录音即作否认", "争议说明应核对完整材料"),
          ],
        },
      ),
      o(
        "record-3-c",
        "请医务科主持下一次沟通",
        1,
        0,
        "医务科登记了争议。明天下午，你必须到场。",
        { flags: ["formal-mediation"], relations: { chief: -1 } },
      ),
    ],
    "record-2",
  ),
  s(
    "cash-4",
    6,
    "rep",
    "cash",
    "可以周转的钱",
    "叶茗在楼梯口等你。「听说你家里急用钱，我可以从个人账户借你一万元。以后要是有合适的会议，你帮我联系一下，行吧？」",
    [
      o(
        "cash-4-a",
        "收下 ¥10,000 的有条件借款",
        0,
        10000,
        "你同意了会议联络条件。借条和转账分别留在两部手机里。",
        {
          privateDebt: 10000,
          flags: ["rep-loan-accepted", "rep-knows-gap"],
          emotion: -3,
        },
      ),
      o(
        "cash-4-b",
        "拒绝，只说已经安排",
        0,
        0,
        "叶茗把手机收起来。「需要的时候再说。」",
        { emotion: -5, flags: ["rep-offer-refused"] },
      ),
      o(
        "cash-4-c",
        "不借钱，请她提供救助渠道",
        1,
        0,
        "她发来公开申请渠道，没有转钱。",
        { stamina: -3, flags: ["rep-knows-gap", "rep-aid-only"] },
      ),
    ],
    "cash-2",
  ),
  s(
    "shift-4",
    7,
    "nurse",
    "shift",
    "转科之前",
    "姜蓉递来一份交接单。李恂那名患者要转科，接收医生要求明确谁做过查体、谁只在场。",
    [
      o(
        "shift-4-a",
        "列出亲历与未见事项",
        1,
        0,
    "你在交接单上分开写明亲历和没见过的事项，再把交接单送给接收医生。",
        { flags: ["li-scope-handed"], relations: { nurse: 1 } },
      ),
      o(
        "shift-4-b",
        "沿用先前的证明",
        0,
        0,
        "原有表述被复制进交接单。你的签名再次出现。",
        { flags: ["li-statement-reused"], emotion: -2 },
      ),
      o(
        "shift-4-c",
        "退回，让原经治医生补充",
        0,
        0,
        "转科等待补件。姜蓉又打了两通电话。",
        { relations: { nurse: -1, peer: -1 }, flags: ["li-handoff-returned"] },
      ),
    ],
    "shift-3",
  ),
  s(
    "research-4",
    7,
    "research",
    "research",
    "经费到账",
    "周乔说项目经费到账了，只能走报销。「如果先垫打印费，票据要留。别把项目钱当成自己的钱。」",
    [
      o(
        "research-4-a",
        "垫付打印并留票据",
        1,
        -300,
    "你为项目垫了三百元打印费，留下了票据，还没收到报销款。",
        { flags: ["project-advance"], emotion: -2 },
      ),
      o(
        "research-4-b",
        "拒绝垫款，等项目付款",
        0,
        0,
    "你没有垫钱，打印只好先等一等。周乔把纸样收进抽屉。",
        { relations: { peer: -1 }, flags: ["project-waited"] },
      ),
      o(
        "research-4-c",
        "用不实票据报销私人支出",
        0,
        800,
        "八百元进入你的账户。不实票据留在项目账里。",
        {
          flags: ["false-invoice", "project-money-used"],
          hazards: [
            risk(
              "F",
              40,
              "用不实项目票据报销私人支出",
              "项目经费须与真实项目支出一致",
            ),
          ],
        },
      ),
    ],
    "research-3",
  ),
  s(
    "record-4",
    8,
    "nurse",
    "record",
    "原件送到哪里",
    "医务科要求提交谈话材料。患者女儿愿意提供原件，但不愿公开有关家庭财务的部分。",
    [
      o(
        "record-4-a",
        "密封交医务科，注明授权范围",
        1,
        0,
        "签收单列明原件、接收人和用途，家属保留自己的副本。",
        { flags: ["record-official-received"], emotion: -2 },
      ),
      o(
        "record-4-b",
        "把录音发进科室大群",
        0,
        0,
        "群里开始讨论她家的经济情况。她收到了转发截图。",
        {
          flags: ["record-public"],
          reputation: -6,
          hazards: [
            risk(
              "C",
              25,
              "超出争议处理范围公开录音",
              "争议材料的使用须限定必要范围",
            ),
          ],
        },
      ),
      o(
        "record-4-c",
        "只作自己的书面陈述",
        1,
        0,
        "医务科把陈述收入卷宗，标明原始录音尚未收到。",
        { flags: ["record-statement-only"], emotion: -4 },
      ),
    ],
    "record-3",
  ),
  s(
    "cash-5",
    8,
    "rep",
    "cash",
    "那份导出表",
    "叶茗发来表格模板，要你填上科室、医生、药品和用量。「你从内部系统导出来就行，十分钟的事。之前的事，我都记着呢。」",
    [
      o(
        "cash-5-a",
        "导出并发送用药明细",
        0,
        4000,
    "你发出了用药明细，随后收到了四千元。聊天和文件上都留着时间。",
        {
          flags: ["prescriptions-exported", "kickback-received"],
          hazards: [
            risk(
              "F",
              60,
              "向利益关联方提供内部用药明细并收款",
              "内部用药数据不得用于个人利益交换",
            ),
          ],
        },
      ),
      o(
        "cash-5-b",
        "拒绝导出，结束这次联系",
        0,
        0,
        "她回复了一个“好”。如果有借款，债务仍然存在。",
        { emotion: -8, flags: ["export-refused"] },
      ),
      o(
        "cash-5-c",
        "只发公开汇总与合规渠道",
        1,
        0,
        "你发的是公开页面，没有交出内部明细。",
        { stamina: -3, flags: ["public-data-only"] },
      ),
    ],
    "cash-4",
  ),
  s(
    "shift-5",
    9,
    "peer",
    "shift",
    "同一张排班表",
    "李恂说调查人员要核对那晚谁在场。「咱们不是也互相帮过忙吗？你跟他们说的时候，别把话说得太绝啊。」",
    [
      o(
        "shift-5-a",
        "保留排班与真实交班记录",
        1,
        0,
        "你保存了自己的材料。它们只证明对应时段，不证明整夜的一切。",
        { flags: ["shift-evidence-held"], emotion: -4 },
      ),
      o(
        "shift-5-b",
        "约好对外使用同一套说法",
        0,
        0,
    "你和李恂在聊天里约好了怎么说，连没核实的内容也写进了这套说法。",
        {
          relations: { peer: 1 },
          flags: ["colluded-witness"],
          hazards: [
            risk(
              "D",
              25,
              "在未核实事实前串联证明口径",
              "调查陈述须独立并基于亲历事实",
            ),
          ],
        },
      ),
      o(
        "shift-5-c",
        "不再讨论，交给医务科核对",
        0,
        0,
        "李恂把手机锁了屏。你们一起走回病区，没有说话。",
        { relations: { peer: -2 }, flags: ["shift-investigation-distance"] },
      ),
    ],
    "shift-4",
  ),
  s(
    "research-5",
    9,
    "research",
    "research",
    "重复的四行",
    "周乔找到了原始表。四行结果来自同一名受试者，课件却写成四人。「这次不能再当作格式问题了。」",
    [
      o(
        "research-5-a",
        "更正样本数，保留发现记录",
        2,
        0,
    "你标出了重复行，更正样本数后，分析结果下降了。你记下了发现问题和修改数据的时间。",
        {
          flags: ["research-known-problem", "research-corrected"],
          stamina: -4,
          relations: { chief: -1 },
        },
      ),
      o(
        "research-5-b",
        "收到，但先不改汇报",
        0,
        0,
        "你知道了问题。汇报稿中的数字保持原样，尚未送审。",
        {
          flags: ["research-known-problem", "research-problem-unfixed"],
          emotion: -6,
        },
      ),
      o(
        "research-5-c",
        "退出后续工作并交出材料",
        1,
        0,
        "你写清自己退出哪些工作、发现了什么问题，再把材料交给周乔。",
        {
          flags: [
            "research-known-problem",
            "research-withdrawn",
            "research-problem-reported",
          ],
          relations: { chief: -1 },
        },
      ),
    ],
    "research-4",
  ),
  s(
    "cash-6",
    10,
    "rep",
    "cash",
    "没有利息的账",
    "叶茗提出把那笔借款和后续联络合并结算。「不用今天还，只要以后还联系得到你。」",
    [
      o(
        "cash-6-a",
        "还清 ¥10,000，终止附加条件",
        0,
        -10000,
        "她确认收到还款。已发生的文件传输或收款不会因此消失。",
        { privateDebt: -10000, flags: ["rep-loan-repaid", "rep-tie-ended"] },
        { all: ["rep-loan-accepted"], none: ["rep-loan-repaid"] },
      ),
      o(
        "cash-6-b",
        "接受继续联络的安排",
        1,
        0,
        "你的名字进了联络名单。借款仍记在私人债务里。",
        { flags: ["rep-liaison-accepted"], emotion: -5 },
      ),
      o(
        "cash-6-c",
        "要求只按原借条处理",
        0,
        0,
        "你拒绝新条件，对方要求按原定日期还款。",
        { flags: ["rep-terms-refused"], emotion: -7 },
      ),
    ],
    "cash-5",
    { all: ["rep-loan-accepted"] },
  ),
  s(
    "record-5",
    10,
    "nurse",
    "record",
    "相差七分钟",
    "录音时间与病程时间相差七分钟。姜蓉把两页纸放在一起。「先核对时钟。别为了对齐，把原记录改掉。」",
    [
      o(
        "record-5-a",
        "写补充说明，保留两个时间",
        1,
        0,
    "你说明了两个设备的时钟为什么有差值，保留了原始记录。",
        { flags: ["time-difference-explained"], emotion: -3 },
      ),
      o(
        "record-5-b",
        "覆盖原记录，改成同一时间",
        0,
        0,
        "页面上的时间一致了。后台保留了修改痕迹。",
        {
          flags: ["record-tampered"],
          hazards: [
            risk(
              "D",
              40,
              "覆盖原始时间记录以消除差异",
              "补记须保留原记录与补记时间",
            ),
          ],
        },
      ),
      o(
        "record-5-c",
        "只把原件交给调查人员",
        0,
        0,
    "你把原件交给调查人员，两个时间仍有差异，还要等他们进一步核对。",
        { flags: ["time-original-submitted"], emotion: -6 },
      ),
    ],
    "record-4",
  ),
  s(
    "shift-6",
    11,
    "chief",
    "shift",
    "到场的人",
    "唐济要求你到场参加核查，家里也等着你接父亲出院。两边安排在同一个小时，都需要你签字。",
    [
      o(
        "shift-6-a",
        "去核查，请家里找陪护",
        1,
        -600,
        "你在核查室签到。父亲由陪护送回家。",
        {
          flags: ["shift-inquiry-attended"],
          relations: { family: -1 },
          emotion: -8,
        },
      ),
      o(
        "shift-6-b",
        "申请改期，先去接父亲",
        2,
        0,
    "对方收下了你的改期申请，考核也因此延期。你到病房拿到了父亲的出院材料。",
        {
          flags: ["father-discharge-attended", "inquiry-postponed"],
          relations: { chief: -1, family: 1 },
        },
      ),
      o(
        "shift-6-c",
        "请李恂跑家里的手续",
        1,
        0,
        "李恂接下委托并到场。你留在核查室，他发来签收照片。",
        {
          flags: [
            "li-family-help-done",
            "li-favor-used",
            "shift-inquiry-attended",
          ],
          emotion: -3,
        },
        {
          all: ["li-owes-time"],
          none: ["li-favor-used", "li-false-witness", "colluded-witness"],
        },
      ),
    ],
    "shift-5",
  ),
  s(
    "research-6",
    11,
    "chief",
    "research",
    "发送之前",
    "你还差最后一步就能提交稿件。唐济说：「今晚就截止了，你决定投不投，签字确认吧。」你已经知道那四行数据重复了。",
    [
      o(
        "research-6-a",
        "只提交修正后的材料",
        2,
        0,
        "你复核样本数和声明后提交，成绩不再像课件上那样好看。",
        {
          flags: ["research-corrected", "paper-submitted-clean"],
          stamina: -5,
          reputation: 3,
        },
      ),
      o(
        "research-6-b",
        "按原数字提交",
        0,
        0,
        "明知重复数据未修正，你仍提交了原稿。回执已发往共同作者邮箱。",
        {
          flags: ["paper-submitted-false"],
          hazards: [
            risk(
              "D",
              60,
              "明知重复样本问题仍提交虚假科研结果",
              "署名提交须对已知的数据真实性负责",
            ),
          ],
        },
      ),
      o(
        "research-6-c",
        "放弃投稿",
        0,
        0,
        "投稿窗口关闭。唐济让你在下一次考核中说明原因。",
        {
          flags: ["paper-not-submitted"],
          relations: { chief: -1 },
          emotion: -8,
        },
      ),
    ],
    "research-5",
  ),
  s(
    "cash-7",
    12,
    "father",
    "cash",
    "钱从哪里来",
    "父亲问你最近为什么总看手机。「缺钱可以跟家里说。你别为了我的事，答应别人不该答应的。」",
    [
      o(
        "cash-7-a",
        "说清账款来源与剩余债务",
        1,
        0,
        "你把几笔钱分开讲。父亲记下欠款，没有替你作承诺。",
        {
          flags: ["family-knows-finance"],
          relations: { family: 1 },
          emotion: -5,
        },
      ),
      o(
        "cash-7-b",
        "说都是工资和积蓄",
        0,
        0,
    "父亲点了点头。你又收到了一条催款消息，没有拿给他看。",
        { flags: ["family-finance-concealed"], emotion: -7 },
      ),
      o(
        "cash-7-c",
        "先不谈钱，陪他吃完饭",
        2,
        -100,
        "饭吃到一半，他问病区忙不忙。借款来源没有谈。",
        { flags: ["family-finance-unspoken"], emotion: 8, san: 4 },
      ),
    ],
    "cash-5",
  ),
  s(
    "record-6",
    12,
    "nurse",
    "record",
    "两个人的证言",
    "姜蓉和患者女儿都提交了材料。她们对一段对话的记忆不同，但都记得你当时在场。",
    [
      o(
        "record-6-a",
        "只说明自己听到与说过的部分",
        1,
        0,
        "你在证言里写清自己听到了什么、说过什么，没有替别人补上自己没听见的对话。",
        { flags: ["record-witness-limited"], emotion: -4 },
      ),
      o(
        "record-6-b",
        "替护士长否认家属的全部陈述",
        0,
        0,
        "姜蓉没有附和。你无法证明的部分也进入了证言。",
        {
          flags: ["record-overbroad-witness"],
          hazards: [
            risk(
              "D",
              25,
              "证言超出亲历范围否认全部陈述",
              "证言应区分观察、转述与推测",
            ),
          ],
        },
      ),
      o(
        "record-6-c",
        "不作证言，提交录音索引",
        1,
        0,
        "材料目录列出了可核对的时间段，调查继续。",
        { flags: ["record-index-submitted"], relations: { nurse: -1 } },
      ),
    ],
    "record-5",
  ),
  s(
    "shift-7",
    13,
    "chief",
    "shift",
    "按下去的名字",
    "唐济把最终说明递给你。涉及李恂那一页，只有你的签名栏还是空的。「你承担哪一段，就写哪一段。」",
    [
      o(
        "shift-7-a",
        "核对原件后签亲历部分",
        2,
        0,
        "你签下自己的部分，附件注明不能证明的事项。",
        { flags: ["shift-final-limited"], emotion: -5 },
      ),
      o(
        "shift-7-b",
        "接受整页责任换取主任支持",
        0,
        0,
    "你签下了整页责任说明。主任答应支持你，却没有在文件上写明你可以免除哪些责任。",
        {
          relations: { chief: 1 },
          flags: ["shift-broad-signature"],
          hazards: [
            risk(
              "D",
              20,
              "未核实全部内容即签署综合责任说明",
              "责任说明须与本人实际行为一致",
            ),
          ],
        },
      ),
      o(
        "shift-7-c",
        "拒绝签署并请求独立复核",
        1,
        0,
    "对方收下了你的复核申请，暂时搁置了考核。",
        { flags: ["shift-independent-review"], relations: { chief: -1 } },
      ),
    ],
    "shift-6",
  ),
  s(
    "research-7",
    13,
    "research",
    "research",
    "询问函",
    "核查人员要求说明四行重复数据、项目票据和每个人的知情时间。周乔已经提交了自己的记录。",
    [
      o(
        "research-7-a",
        "提交发现、使用与更正的时间线",
        2,
        0,
        "你提交了真实时间线。原件能证明来源，也能证明何时已经知道问题。",
        { flags: ["research-truth-submitted"], emotion: -6 },
      ),
      o(
        "research-7-b",
        "把重复行说成四名新患者",
        0,
        0,
        "新陈述和原始表无法对应。你的回答留在询问笔录中。",
        {
          flags: ["research-lied-inquiry"],
          hazards: [
            risk(
              "D",
              30,
              "核查时将重复记录谎称为独立样本",
              "核查说明不得虚构不存在的受试者",
            ),
          ],
        },
      ),
      o(
        "research-7-c",
        "申请查阅材料后再答复",
        1,
        0,
    "对方同意延长你的答复期限，暂时不确认评审岗位。",
        { flags: ["research-reply-pending"], emotion: -8 },
      ),
    ],
    "research-6",
  ),
  s(
    "cash-8",
    14,
    "rep",
    "cash",
    "以后的联络人",
    "叶茗发来聘用意向，工作内容是联络医院。她说：「你知道哪些门能进去。」签约截止在今晚。",
    [
      o(
        "cash-8-a",
        "接受联络岗位",
        1,
        0,
        "你确认了岗位。意向书生效，既有借款和已发生的利益往来另行结算。",
        { flags: ["liaison-job-obtained"], emotion: 5 },
      ),
      o(
        "cash-8-b",
        "拒绝，保留全部往来记录",
        1,
        0,
        "你拒绝签约，保存了收款、借款和文件往来的原件。",
        { flags: ["finance-records-held"], emotion: -5 },
      ),
      o(
        "cash-8-c",
        "暂不签约，承诺明天回复",
        0,
        0,
        "她没有延长截止时间。岗位未确认。",
        { flags: ["liaison-job-unconfirmed"], emotion: -7 },
      ),
    ],
    "cash-7",
    { any: ["rep-liaison-accepted", "prescriptions-exported", "public-data-only"] },
  ),
  s(
    "record-7",
    13,
    "nurse",
    "record",
    "不能撤回的副本",
    "患者女儿说已经举报，也已把录音交给受理窗口。「我不要你删，我要你解释。」",
    [
      o(
        "record-7-a",
        "提交完整说明并接受质询",
        2,
        0,
        "你解释自己的判断和后续变化，保留了不能确定的部分。",
        { flags: ["record-full-response"], emotion: -5 },
      ),
      o(
        "record-7-b",
        "要求她先撤回举报再沟通",
        0,
        0,
        "她拒绝了。要求撤回举报的这句话成为补充材料。",
        {
          flags: ["complaint-pressure"],
          hazards: [
            risk(
              "C",
              25,
              "以撤回举报作为进一步沟通条件",
              "争议中的必要沟通不得附撤诉条件",
            ),
          ],
        },
      ),
      o(
        "record-7-c",
        "通过医务科联系调解",
        1,
        -500,
        "医务科收到调解申请，家属尚未表示接受。",
        { flags: ["mediation-requested"], emotion: -3 },
      ),
    ],
    "record-6",
  ),
  s(
    "shift-8",
    14,
    "peer",
    "shift",
    "还回来的钥匙",
    "李恂把值班室钥匙放回桌上。「以后还在一个科室吗？」他没有问调查结果。",
    [
      o(
        "shift-8-a",
        "把人情与证言分开说清楚",
        1,
        0,
        "你谢过李恂实际帮过你的事，也告诉他，你不会改掉已经作出的真实陈述。",
        { flags: ["shift-boundary-kept"], emotion: 3 },
      ),
      o(
        "shift-8-b",
        "答应以后继续互相兜底",
        0,
        0,
        "你们保留了联系。这句话没有改变卷宗中的任何事实。",
        { flags: ["shift-dependent-tie"], relations: { peer: 1 }, emotion: -5 },
      ),
      o(
        "shift-8-c",
        "收下钥匙，不再联系",
        0,
        0,
        "钥匙进了抽屉。李恂离开时没有关灯。",
        { flags: ["shift-tie-cut"], relations: { peer: -1 }, emotion: -3 },
      ),
    ],
    "shift-7",
  ),
  s(
    "research-8",
    14,
    "chief",
    "research",
    "岗位",
    "唐济通知你，项目下一阶段需要一个对外负责人。「评审还没结束。接下这个岗位，后面的询问也由你来答。」",
    [
      o(
        "research-8-a",
        "接受岗位与后续答复职责",
        1,
        0,
    "科室发出了你的任命通知。以后你要回答有关项目的询问，补交材料，并负责整改。",
        { flags: ["project-role-obtained"], reputation: 5, emotion: -4 },
      ),
      o(
        "research-8-b",
        "只完成已承诺的移交",
        2,
        0,
    "接收人签好了移交单。你仍要承担署名责任，对自己提交过的材料负责。",
        { flags: ["research-handoff-complete"], stamina: -4 },
      ),
      o(
        "research-8-c",
        "辞去项目工作",
        0,
        0,
    "你辞去了项目工作。这项成果不再计入考核，已经开始的调查仍会继续。",
        { flags: ["research-role-left"], relations: { chief: -1 }, emotion: 3 },
      ),
    ],
    "research-7",
  ),
  s(
    "record-8",
    14,
    "nurse",
    "record",
    "谈话室的门",
    "最后一次谈话结束，患者女儿收起手机。姜蓉站在门旁，等你把自己的材料收好。",
    [
      o(
        "record-8-a",
        "确认材料签收，再离开",
        1,
        0,
    "你和家属各留了一份签收单，她保留了自己的唯一原件。",
        { flags: ["record-closure-receipt"], emotion: 3 },
      ),
      o(
        "record-8-b",
        "道歉，但不作无法兑现的承诺",
        1,
        0,
        "你为实际发生的疏漏道歉。她说会等调查结果。",
        { flags: ["record-apology"], emotion: -3, san: 3 },
      ),
      o(
        "record-8-c",
        "不再说话，回病区",
        0,
        0,
        "门在身后关上。材料已经留在卷宗里。",
        { flags: ["record-silent-close"], emotion: -6 },
      ),
    ],
    "record-7",
  ),
  s(
    "cross-1",
    8,
    "nurse",
    "cross",
    "同一小时",
    "项目补件与病区家属沟通撞在同一小时。周乔只能帮你做一件事，姜蓉等你报出安排。",
    [
      o(
        "cross-1-a",
        "自己去沟通，请周乔送项目原件",
        2,
        0,
    "周乔签收送件委托后，把原件送到了项目窗口。你按时来到谈话室。",
        {
          flags: ["cross-project-received", "cross-talk-attended"],
          stamina: -5,
        },
      ),
      o(
        "cross-1-b",
        "自己送件，请医务科改沟通时间",
        1,
        0,
    "你送去的项目材料已经有人签收，医务科改了沟通时间。家属为此又请了半天假。",
        { flags: ["cross-project-received"], emotion: -6, reputation: -3 },
      ),
      o(
        "cross-1-c",
        "放弃这次项目补件，留下沟通",
        1,
        0,
    "你按时和家属沟通，没有补交项目材料，这次缺件被记入考核。",
        {
          flags: ["cross-talk-attended", "cross-project-missed"],
          relations: { chief: -1 },
        },
      ),
    ],
    undefined,
    { all: ["research-worked", "recording-exists"] },
  ),
  s(
    "cross-2",
    12,
    "research",
    "cross",
    "同一份账与表",
    "核查人员把报销单和各版数据并排放好，要求你分别说明钱去了哪里，以及数据何时改过。",
    [
      o(
        "cross-2-a",
        "逐笔解释款项，逐版解释数据",
        2,
        0,
    "你分别提交了款项往来和数据修改的时间线，没有用一份说明去证明另一件事。",
        { flags: ["cross-double-account"], emotion: -5 },
      ),
      o(
        "cross-2-b",
        "只解释钱，拒绝谈数据",
        1,
        0,
    "核查人员收下了你的款项说明，还等着你回答数据的问题。",
        { flags: ["cross-money-only"], emotion: -6 },
      ),
      o(
        "cross-2-c",
        "用主任签字代替本人说明",
        0,
        0,
        "核查人员记下主任签字，同时要求你继续说明本人的行为。",
        {
          flags: ["cross-deferred-to-chief"],
          relations: { chief: -1 },
          emotion: -8,
        },
      ),
    ],
    undefined,
    {
      all: ["research-known-problem"],
      any: ["false-invoice", "project-advance"],
    },
  ),
  s(
    "family-wedding",
    7,
    "father",
    "family",
    "婚礼前的电话",
    "家里商量婚事，预算又加了一笔。「别人都这么办。」你看着工资到账短信，病区也在等人。",
    [
      o(
        "family-wedding-a",
        "拿出 ¥3,000，暂不回家",
        0,
        -3000,
    "家里收到了你转去的钱，还在等你答复是否参加婚礼。",
        { emotion: -5, flags: ["wedding-paid"] },
      ),
      o(
        "family-wedding-b",
        "留时间把预算说清楚",
        2,
        0,
        "电话打了四十分钟。有人不高兴，金额没有继续增加。",
        {
          flags: ["family-boundary-talk"],
          relations: { family: 1 },
          stamina: -4,
        },
      ),
      o(
        "family-wedding-c",
        "让他们自行决定，不出钱",
        0,
        0,
        "家人在电话里说知道了，之后也没在群里再问你。",
        { relations: { family: -1 }, emotion: -10, flags: ["wedding-absent"] },
      ),
    ],
  ),
];

export function conditionMet(
  facts: Record<string, unknown>,
  c?: Condition,
  cash = 0,
  relations: Record<string, number> = {},
): boolean {
  return (
    !c ||
    ((!c.all || c.all.every((x) => !!facts[x])) &&
      (!c.any || c.any.some((x) => !!facts[x])) &&
      (!c.none || c.none.every((x) => !facts[x])) &&
      (c.cash === undefined || cash >= c.cash) &&
      (!c.relation || (relations[c.relation[0]] ?? 0) >= c.relation[1]))
  );
}
